TrainingArguments:
  num_train_epochs: 1         # 1 epoch = 52 steps is very little learning; consider more
  learning_rate: 0.00002
  warmup_steps: 5           
  per_device_train_batch_size: 1
  weight_decay: 0.01
  logging_steps: 10
  evaluation_strategy: steps
  eval_steps: 10
  save_steps: 10
  gradient_accumulation_steps: 16